In [1]:
import numpy as np
import MasterClassMultiCLF
import pandas as pd

In [2]:
w = MasterClassMultiCLF.Master("IRIS1.csv")

In [3]:
w.pass_features(['A', 'B', 'C'])

In [5]:
w.pass_labels("Label")

In [6]:
w.split_data(0.3)

In [7]:
w.classifiermulticlf()

### URL = http://scikit-learn.org/stable/modules/naive_bayes.html

In [8]:
w.NB()

simple accuracy :  0.766666666667
confusion matrix :  [[11  0  0]
 [ 1  7  4]
 [ 0  2  5]]
precision: [ 0.91666667  0.77777778  0.55555556]
recall: [ 1.          0.58333333  0.71428571]
fscore: [ 0.95652174  0.66666667  0.625     ]
support: [11 12  7]
Time spent in Naive Bayes is =  0.239013671875


### LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='liblinear', max_iter=100, multi_class='ovr', verbose=0, warm_start=False, n_jobs=1

### URL = http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [10]:
w.LogReg(C=0.5)

simple accuracy :  0.633333333333
confusion matrix :  [[11  0  0]
 [ 0  1 11]
 [ 0  0  7]]
precision: [ 1.          1.          0.38888889]
recall: [ 1.          0.08333333  1.        ]
fscore: [ 1.          0.15384615  0.56      ]
support: [11 12  7]
Time spent in Logistic Regression is =  0.01800084114074707


### DecisionTreeClassifier(criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_split=1e-07, class_weight=None, presort=False)

### http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier

In [11]:
w.DecTree(min_samples_split = 50)

simple accuracy :  0.6
confusion matrix :  [[11  0  0]
 [ 1  0 11]
 [ 0  0  7]]
precision: [ 0.91666667  0.          0.38888889]
recall: [ 1.  0.  1.]
fscore: [ 0.95652174  0.          0.56      ]
support: [11 12  7]
Time spent in Decision Tree is =  0.09400534629821777


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### AdaBoostClassifier(base_estimator=None, n_estimators=50, learning_rate=1.0, algorithm='SAMME.R', random_state=None)

### URL = http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

In [12]:
w.AdaBoostClf()

simple accuracy :  0.766666666667
confusion matrix :  [[11  0  0]
 [ 0  6  6]
 [ 0  1  6]]
precision: [ 1.          0.85714286  0.5       ]
recall: [ 1.          0.5         0.85714286]
fscore: [ 1.          0.63157895  0.63157895]
support: [11 12  7]
Time spent in AdaBoost is =  0.14900827407836914


### SVC(C=1.0, kernel='rbf', degree=3, gamma='auto', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape=None, random_state=None)

### URL = http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

In [13]:
w.SVM(kernel = 'poly')

simple accuracy :  0.766666666667
confusion matrix :  [[11  0  0]
 [ 0  7  5]
 [ 0  2  5]]
precision: [ 1.          0.77777778  0.5       ]
recall: [ 1.          0.58333333  0.71428571]
fscore: [ 1.          0.66666667  0.58823529]
support: [11 12  7]
Time spent in Support Vector Machine is =  0.4450252056121826


### KNeighborsClassifier(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=1, **kwargs)

### URL = http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [14]:
w.KNN()

simple accuracy :  0.666666666667
confusion matrix :  [[11  0  0]
 [ 1  6  5]
 [ 0  4  3]]
precision: [ 0.91666667  0.6         0.375     ]
recall: [ 1.          0.5         0.42857143]
fscore: [ 0.95652174  0.54545455  0.4       ]
support: [11 12  7]
Time spent in K Nearest Neighbor is =  0.8770501613616943


### RandomForestRegressor(n_estimators=10, criterion='mse', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_split=1e-07, bootstrap=True, oob_score=False, n_jobs=1, random_state=None, verbose=0, warm_start=False)

### URL = http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html

In [15]:
w.RanForClf()

simple accuracy :  0.7
confusion matrix :  [[11  0  0]
 [ 0  7  5]
 [ 0  4  3]]
precision: [ 1.          0.63636364  0.375     ]
recall: [ 1.          0.58333333  0.42857143]
fscore: [ 1.          0.60869565  0.4       ]
support: [11 12  7]
Time spent in Random Forest is =  0.28401637077331543
